version: '3.4'

services:
  redis:
    image: redis:alpine
  mongo:
    image: mongo:latest
  short-url:
    image: ${REGISTRY:-eshopdapr}/basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    depends_on:
      - mongo
      - redis
